### ISSUE TITLE
Changing Area crashes the game with new update

### ISSUE THREAD

**Issue by SnaikerSDM** [TRPG0/BRC-BoostColors#1]
![image](https://github.com/TRPG0/BRC-BoostColors/assets/102826768/78351aa4-ff78-4ac0-b7ae-e0e4dc3fd20f)
Trying to switch areas crashes the game. Highly reproduceable it seems

**Comment by SnaikerSDM** [comment]
In the process I'll try disabling mods, see if it conflicts

**Comment by TRPG0** [comment]
Whoops. Fixed it
